# Generated by Django 5.1.7 on 2025-04-21 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0002_alter_tutor_admission_criteria_alter_tutor_photo'),
    ]

    operations = [
    ]
