# Generated by Django 5.1.7 on 2025-04-09 08:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
